### PR TITLE
Minimum & Maximum giveaway prize length

### LINKED ISSUE #322: [Feature Request] Check giveaway name length
### Is your feature request related to a problem?

Check for length of giveaway prize

### Describe the solution you'd like

It would be better for the sniper to check if the gw has lower characters then 4 characters this will avoid getting caught or the user can customise it ```skip: {
 Enabled = true,
 Lessthen: 4
}
```

### How will this be beneficial to the sniper

Less sus (again)

### Please provide an example of usage of this feature

It would auto skip gws called "a", "1" damn admins get smarter every day

### PR DESCRIPTION
**Pull request by Craftzman7**
Closes #322

### CODE REVIEW

**Comment by Craftzman7** [comment]
Looks like a commit from another pull request got dropped here... I'll mark as draft and fix it

**Comment by IShowLight-7777** [comment]
If your going to yoink all of my ideas why not steal the message randomizer

**Comment by Craftzman7** [comment]
I'm simply implementing feature requests?

**Comment by Craftzman7** [comment]
> If your going to yoink all of my ideas why not steal the message randomizer 

Looks like someone already "stole" it in #372 🤣

**Pull request merged**
