### PR TITLE
Add channel blacklisting

### LINKED ISSUE #350: [Feature Request] Blacklist certain channels on the nitro sniper
### Is your feature request related to a problem?

I would like for snip nitro but without some channel, can you make it have blacklist channel nitro snip. 

### Describe the solution you'd like

User can input blacklist id channel in config file

### How will this be beneficial to the sniper

some sniper is staff/mod of server. We give nitro to buyer but they can't faster than bot

### Please provide an example of usage of this feature

I was claimed the customer's nitro, so i must compensation this

### PR DESCRIPTION
**Pull request by Craftzman7**
Closes #350

### CODE REVIEW

**Comment by IShowLight-7777** [comment]
Why i was working on one >:(

**Comment by Craftzman7** [comment]
I saw the issue and thought I might as well do it. Took me 2 minutes to do. 🤷‍♂️

**Comment by IShowLight-7777** [comment]
Well atleast imma get advanced

**Comment by IShowLight-7777** [comment]
Because PPL like to name their channels impossible characters like the bold version of stuff

**Comment by Craftzman7** [comment]
What are you even talking about?

**Pull request merged**
